### ISSUE TITLE
access omero.server from outside of the docker container?

### ISSUE THREAD

**Issue by litaochen** [openmicroscopy/omero-server-docker#22]
I run the omero.server docker image and was able to login with root account from within the container. But on the host, I did not see anything listens to port 4064. When I tried to log in through omero.web from the host it always complains server is not responding. 
What is the expected behavior? Can we run omero.server container and access the server from outside of the container or oven from a remote machine?
Thanks.

**Comment by joshmoore** [comment]
Definitely. Can you share how you are starting your containers so we can help make a suggestion?

**Comment by litaochen** [comment]
Thanks Josh,
I used this omero.server container: https://hub.docker.com/r/openmicroscopy/omero-server
Start the container by:
```
docker run -d --name postgres -e POSTGRES_PASSWORD=postgres postgres
```
```
docker run -d --name omero-server --link postgres:db \
    -e CONFIG_omero_db_user=postgres \
    -e CONFIG_omero_db_pass=postgres \
    -e CONFIG_omero_db_name=postgres \
    -e ROOTPASS=omero-root-password \
    -p 4063:4063 -p 4064:4064 \
    openmicroscopy/omero-server
```

Try to connect to the server using image: https://hub.docker.com/r/openmicroscopy/omero-web-standalone

start the web server using:
```
    docker run -d --name omero-web \
    -e OMEROHOST=127.0.0.1 \
    -p 4080:4080 \
    openmicroscopy/omero-web-standalone
```

Always get "server not responding" message

When checking port listening status with:
```
netstat -a  | grep LISTEN
```
got this:
```
tcp4       0      0  localhost.freeciv      *.*                    LISTEN
tcp4       0      0  192.168.31.26.freeciv  *.*                    LISTEN
tcp4       0      0  localhost.19421        *.*                    LISTEN
tcp4       0      0  localhost.ipp          *.*                    LISTEN
tcp6       0      0  localhost.ipp          *.*                    LISTEN
tcp6       0      0  *.54254                *.*                    LISTEN
tcp4       0      0  *.54254                *.*                    LISTEN
tcp4       0      0  localhost.socks        *.*                    LISTEN
tcp4       0      0  *.8090                 *.*                    LISTEN
tcp6       0      0  localhost.ice-router   *.*                    LISTEN
tcp4       0      0  *.ice-router           *.*                    LISTEN
tcp6       0      0  localhost.ice-srouter  *.*                    LISTEN
tcp4       0      0  *.ice-srouter          *.*                    LISTEN
tcp6       0      0  localhost.4080         *.*                    LISTEN
tcp4       0      0  *.4080                 *.*                    LISTEN
tcp4       0      0  localhost.mysql        *.*                    LISTEN
tcp4       0      0  localhost.30100        *.*                    LISTEN
tcp4       0      0  localhost.50154        *.*                    LISTEN
tcp4       0      0  localhost.60001        *.*                    LISTEN
```

Did not see any process listening on port 4064.

Did I miss anything?

**Comment by joshmoore** [comment]
Hi @litaochen. The issue you are seeing is quite similar to the one I explained in https://github.com/openmicroscopy/omero-web-docker/issues/27#issuecomment-458448044

Namely within the within the `omero-web-standalone` image, 127.0.0.1 doesn't refer to what you think it refers to. Either you will need to use the host ip address (since you mapped 4064 and 4063) or you will need to use the name of the `omero-server` container that you linked. e.g.

```
 docker run --name g-omero-web --rm -d \
-    -e OMEROHOST=localhost \
+    --link g-omero-server:omero \
+    -e OMEROHOST=omero \
     -p 4080:4080 \
     openmicroscopy/omero-web-standalone
```

**Comment by litaochen** [comment]
Ahh! Changing to host IP worked! 
Thanks, Josh!

**Comment by joshmoore** [comment]
Glad to hear it!
